# Generated by Django 4.2.17 on 2025-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cybersecuritysalary_jobvacancyshare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='average_salary',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='city',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='notes',
        ),
        migrations.AddField(
            model_name='geography',
            name='graph',
            field=models.ImageField(blank=True, null=True, upload_to='geography', verbose_name='График'),
        ),
        migrations.AddField(
            model_name='geography',
            name='table',
            field=models.TextField(blank=True, null=True, verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='geography',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='geography',
            name='title',
            field=models.CharField(default='География', max_length=100, verbose_name='Заголовок'),
        ),
    ]
