# Generated by Django 4.2.17 on 2025-01-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_geography_average_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='table',
        ),
        migrations.AddField(
            model_name='geography',
            name='salary_table',
            field=models.TextField(blank=True, null=True, verbose_name='Таблица зарплат'),
        ),
        migrations.AddField(
            model_name='geography',
            name='vacancy_table',
            field=models.TextField(blank=True, null=True, verbose_name='Таблица вакансий'),
        ),
    ]
