# Generated by Django 4.2.17 on 2025-01-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('skills', models.CharField(max_length=255, verbose_name='Навыки')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('salary', models.CharField(max_length=100, verbose_name='Оклад')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
